name: testapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^5.2.4
  injectable: ^2.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
